<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SenderKeyStateStructure\SenderMessageKey instead.
     * @deprecated
     */
    class SenderKeyStateStructure_SenderMessageKey {}
}
class_exists(SenderKeyStateStructure\SenderMessageKey::class);
@trigger_error('Localstorage\SenderKeyStateStructure_SenderMessageKey is deprecated and will be removed in the next major release. Use Localstorage\SenderKeyStateStructure\SenderMessageKey instead', E_USER_DEPRECATED);

