<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SenderKeyStateStructure\SenderChainKey instead.
     * @deprecated
     */
    class SenderKeyStateStructure_SenderChainKey {}
}
class_exists(SenderKeyStateStructure\SenderChainKey::class);
@trigger_error('Localstorage\SenderKeyStateStructure_SenderChainKey is deprecated and will be removed in the next major release. Use Localstorage\SenderKeyStateStructure\SenderChainKey instead', E_USER_DEPRECATED);

