<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SenderKeyStateStructure\SenderSigningKey instead.
     * @deprecated
     */
    class SenderKeyStateStructure_SenderSigningKey {}
}
class_exists(SenderKeyStateStructure\SenderSigningKey::class);
@trigger_error('Localstorage\SenderKeyStateStructure_SenderSigningKey is deprecated and will be removed in the next major release. Use Localstorage\SenderKeyStateStructure\SenderSigningKey instead', E_USER_DEPRECATED);

