<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SessionStructure\PendingKeyExchange instead.
     * @deprecated
     */
    class SessionStructure_PendingKeyExchange {}
}
class_exists(SessionStructure\PendingKeyExchange::class);
@trigger_error('Localstorage\SessionStructure_PendingKeyExchange is deprecated and will be removed in the next major release. Use Localstorage\SessionStructure\PendingKeyExchange instead', E_USER_DEPRECATED);

