<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SessionStructure\Chain\ChainKey instead.
     * @deprecated
     */
    class SessionStructure_Chain_ChainKey {}
}
class_exists(SessionStructure\Chain\ChainKey::class);
@trigger_error('Localstorage\SessionStructure_Chain_ChainKey is deprecated and will be removed in the next major release. Use Localstorage\SessionStructure\Chain\ChainKey instead', E_USER_DEPRECATED);

