<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SessionStructure\PendingPreKey instead.
     * @deprecated
     */
    class SessionStructure_PendingPreKey {}
}
class_exists(SessionStructure\PendingPreKey::class);
@trigger_error('Localstorage\SessionStructure_PendingPreKey is deprecated and will be removed in the next major release. Use Localstorage\SessionStructure\PendingPreKey instead', E_USER_DEPRECATED);

