<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SessionStructure\Chain instead.
     * @deprecated
     */
    class SessionStructure_Chain {}
}
class_exists(SessionStructure\Chain::class);
@trigger_error('Localstorage\SessionStructure_Chain is deprecated and will be removed in the next major release. Use Localstorage\SessionStructure\Chain instead', E_USER_DEPRECATED);

