<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalStorageProtocol.proto

namespace Localstorage;

if (false) {
    /**
     * This class is deprecated. Use Localstorage\SessionStructure\Chain\MessageKey instead.
     * @deprecated
     */
    class SessionStructure_Chain_MessageKey {}
}
class_exists(SessionStructure\Chain\MessageKey::class);
@trigger_error('Localstorage\SessionStructure_Chain_MessageKey is deprecated and will be removed in the next major release. Use Localstorage\SessionStructure\Chain\MessageKey instead', E_USER_DEPRECATED);

